name: Skip Check
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate EPUBs (skip manifest check)
        run: npm run manifest:check
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SKIP_CHECK: 'true'

      - name: Check for new files
        id: data
        run: echo "porcelain=$(git status --porcelain)" >> $GITHUB_OUTPUT

      - name: Commit latest manifest version
        if: steps.data.outputs.porcelain
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "D2 Grimoire Epub Bot"

          git checkout --orphan tmp
          git add -A
          git commit -m 'Grimoire Generated'
          git branch -D master
          git branch -m master
          git push -f origin master
